# Generated by Django 3.1.5 on 2021-03-04 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_web_servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_cliente',
            name='apellido',
            field=models.CharField(default='charfield', max_length=40),
        ),
        migrations.AddField(
            model_name='registro_cliente',
            name='direccion',
            field=models.CharField(default='charfield', max_length=50),
        ),
        migrations.AddField(
            model_name='registro_cliente',
            name='nombre',
            field=models.CharField(default='charfield', max_length=40),
        ),
        migrations.AddField(
            model_name='registro_cliente',
            name='telefono',
            field=models.IntegerField(default='integer'),
        ),
        migrations.AddField(
            model_name='registro_servicios',
            name='apellido',
            field=models.CharField(default='charfield', max_length=40),
        ),
        migrations.AddField(
            model_name='registro_servicios',
            name='direccion',
            field=models.CharField(default='charfield', max_length=50),
        ),
        migrations.AddField(
            model_name='registro_servicios',
            name='email',
            field=models.EmailField(default='charfield', max_length=254),
        ),
        migrations.AddField(
            model_name='registro_servicios',
            name='matricula',
            field=models.BooleanField(default='charfield'),
        ),
        migrations.AddField(
            model_name='registro_servicios',
            name='nombre',
            field=models.CharField(default='charfield', max_length=40),
        ),
        migrations.AddField(
            model_name='registro_servicios',
            name='telefono',
            field=models.IntegerField(default='integer'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(default='charfield', max_length=100),
        ),
    ]
