# Generated by Django 3.1.5 on 2021-03-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_web_servicios', '0002_auto_20210303_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_cliente',
            name='telefono',
            field=models.IntegerField(default='integerfield'),
        ),
        migrations.AlterField(
            model_name='registro_servicios',
            name='telefono',
            field=models.IntegerField(default='integerfield'),
        ),
    ]
